### ISSUE TITLE
Yaesu G-5500

### ISSUE THREAD

**Issue by UW5EJA** [dh1tw/remoteRotator#3]
Hello Tobias.

RemoteRotator is great idea, interesting and user-friendly program.
But when I run remoteRotator in Windows XP or Windows 8 after 30 seconds, I get the error:

"serial port read error <'Rotator on COM3'>: multiple Read calls return no data or error
panic: close of nil channel"

Could you please solve this problem?

I use version 0.4.1. Thank you!

![remoterotator](https://user-images.githubusercontent.com/40354851/41529627-6d81c5e8-72f6-11e8-93dd-1c509025f00d.jpg)

**Comment by dh1tw** [comment]
Hi,
Can you give me some more background information on your setup?
- What kind of rotator Control are you using? The original Yaesu one or an Interface like EA4TX ARS?
- Can you verify with another program that the Rotator is actually Working properly on COM3?
- Is remoteRotator Able to communicate with the Rotator or does it Not work at all?
- can you paste your remoteRotator.toml Config file?

Tnx
Tobias

**Comment by dh1tw** [comment]
Hi Victor, 

let's try to solve the easy things first: 
Can you try running `remoteRotator.exe web` on the Windows8 machine? The mDNS library I'm using requires unfortunately a IPv6 stack, which WindowsXP probably doesn't have. Windows8 on the other hand should have an IPv6 stack build in.

wrt to the "serial port read error": 
I saw on the website of the ERC that ERC supports basically 3 protocols:
- Hygain DCU-1 with extension for position-feedback
- Yaesu GS232A with extension for DUAL-Azimuth (by VE2DX)
- Yaesu GS232B with extension for DUAL-Azimuth (by VE2DX)
Can you select the protocol in any way? GS232A/B should work with remoteRotator.

In order to communicate directly with the rotator, you can open a serial console using [putty](https://www.putty.org/). You can find the commands for talking to the ERC (via the GS232A/B protocol) for example [here](http://www.radiomanual.info/schemi/YAESU_ACC/Yaesu_GS-23_GS-232_user.pdf).

But if other applications (like HRD or Simplesat) can talk on the same machine directly with the ERC, the problem might be somewhere in my code.

hw? 

73 Tobias

**Comment by UW5EJA** [comment]
Hello Todias.

In Windows 8 was the similar error. After the launch "remote Rotator web" in the browser was only "Searching for rotators...".

I launched remoteRotator in Ubuntu 14.04 and it`s working well. Thank you!

I wrote flag "--discovery-enabled", but after running remoteRotator I saw in command line:
"discovery disabled; the HTTP server must listen on an accessible network interface"
What does it mean?

73!
Victor

**Comment by dh1tw** [comment]
Hi Victor,

that means that you are listening on localhost only. You should listen on external network interfaces, e.g. ``0.0.0.0`` for all interfaces. 

If you enable discovery and listen on all interfaces, then the rotator should also be detected properly on other instances.

hw?

73 Tobias

**Comment by UW5EJA** [comment]
Hi Tobias,

Thank you. When I added flag `-w 0.0.0.0` I was able to connect from a local network.

Сould I specify a few IP addresses or only choose `127.0.0.1` / `0.0.0.0`" ?
I read about access to remoteRotator with authentication in Wiki "Expose remoteRotator to the Internet" - This is a great feature.

73!
With the best regards
Victor

**Comment by dh1tw** [comment]
by listening on `0.0.0.0` you are automatically listening on all interfaces. If you would like to limit it to a particular address (in the unlikely case that your computer has two network cards and is connected to two different networks), you could specify one particular interface e.g. `192.168.1.30`...

Does that help?

73 Tobias

**Comment by UW5EJA** [comment]
Hi Tobias.

Just wanted to ask you if this is possible. Thanks for the answer.
I think that the Caddy web server with authentication is an excellent solution.

With the best regards!
Victor

**Comment by dh1tw** [comment]
Hi @UW5EJA,

my apologies that it took so long to create a new release. I have fixed the windows problems - although support for WindowsXP has been removed, but it will work fine for > Windows 7. You can download the latest release from the [release page](https://github.com/dh1tw/remoteRotator/releases/tag/v0.5.2).

Feel free to re-open this issue if remoteRotator doesn't work as expected.
